apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: env
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: railsapp
        image: nadamohamed2222/passwd:v1
        env:
        - name: NAME
          value: vvvvvvvvv
        - name: PASSWORD
          valueFrom: 
            secretKeyRef:
              name: password
              key: PASSWORD
        ports:
        - containerPort: 3000

