apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: current
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: rails
    spec:
      containers:
      - name: railsapp
        image: nadamohamed2222/rub:v1
        ports:
        - containerPort: 3000

